version: '2'

volumes:
  dbdata_mysql_maria:

services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '${APACHE_PORT}:80'
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.5.2
    container_name: americor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - "dbdata_mysql_maria:/var/lib/mysql"
    ports:
      - ${DB_PORT}:3306